#!/usr/bin/with-contenv bash

echo "[AirConnect-AIRUPNP] Launching AIRUPNP ..."

retries=0
max_retries=5

while [ $retries -lt $max_retries ]; do
  if [ -z "$AIRUPNP_VAR" ]; then
    echo "[AirConnect-AIRUPNP] AIRUPNP_VAR is NOT present, launching with standard launch variables"
    /usr/bin/airupnp-docker -Z -l 1000:2000
  elif [ "$AIRUPNP_VAR" = "kill" ]; then
    echo "[AirConnect-AIRUPNP] AIRUPNP_VAR set to kill, skipping AIRUPNP service launch"
    exit 0
  else
    echo "[AirConnect-AIRUPNP] AIRUPNP_VAR is present, launching with custom launch variables: $AIRUPNP_VAR"
    /usr/bin/airupnp-docker -Z $AIRUPNP_VAR
  fi

  retries=$((retries + 1))
  echo "[AirConnect-AIRUPNP] airupnp crashed. Retry $retries/$max_retries in 5 seconds..."
  sleep 5
done

echo "[AirConnect-AIRUPNP] airupnp failed too many times, giving up"
exit 1
