#!/usr/bin/with-contenv bash

# Check for VAR - kill, custom, default
if [ "$AIRUPNP_VAR" = "kill" ]; then
  echo "AIRUPNP_VAR set to kill, killing airupnp service launch"
  exit 0
elif [ "$AIRUPNP_VAR" != "kill" ]; then
  echo "AIRUPNP_VAR present, using custom user airupnp launch variables"
  exec /bin/airupnp-linux-x86_64 "$AIRUPNP_VAR"
else
  echo "No AIRUPNP_VAR present, continuing with standard airupnp launch variables"
  exec /bin/airupnp-linux-x86_64 -l 1000:2000
fi