#!/usr/bin/with-contenv bash

# Check for VAR - default, kill, custom
if [ -z "$AIRUPNP_VAR" ]; then
  echo "No AIRUPNP_VAR present, continuing with standard airupnp launch variables"
  exec /bin/airupnp-linux-x86_64 -l 1000:2000
elif [ "$AIRUPNP_VAR" = "kill" ]; then
  echo "AIRUPNP_VAR set to kill, skipping airupnp service launch"
else
  echo "AIRUPNP_VAR present, using custom user airupnp launch variables"
  exec /bin/airupnp-linux-x86_64 $AIRUPNP_VAR
fi

# Check for VAR - default, kill, custom
if [ -z "$AIRCAST_VAR" ]; then
  echo "No AIRCAST_VAR present, continuing with standard aircast launch variables"
  exec /bin/aircast-linux-x86_64
elif [ "$AIRCAST_VAR" = "kill" ]; then
  echo "AIRCAST_VAR set to kill, skipping aircast service launch"
else
  echo "AIRCAST_VAR present, using custom user aircast launch variables"
  exec /bin/aircast-linux-x86_64 $AIRCAST_VAR
fi