#!/usr/bin/with-contenv bash

echo "Checking for valid arch options"
case $ARCH_VAR in
  x86-64)
    echo "Proceeding with x86-64 arch"
    ;;
  aarch64)
    echo "Proceeding with aarch64 arch"
    ;;
  arm)
    echo "Proceeding with arm arch"
    ;;
  *)
    echo "Unrecognized or invalid arch selection, CANCELING INSTALL"
    echo "========== FAILURE DETECTED ========="
    echo "YOUR CONTAINER WILL NOT WORK, PLEASE ADDRESS OR OPEN AN ISSUE"
    exit 1
    ;;
esac

# Adjusting process names in supervisord for Architecture differences
[ "$ARCH_VAR" != "x86-64" ] && sed -i 's;process_name = airupnp-x86-64;process_name = airupnp-'"$ARCH_VAR"';' /etc/supervisord.conf
[ "$ARCH_VAR" != "x86-64" ] && sed -i 's;process_name = aircast-x86-64;process_name = aircast-'"$ARCH_VAR"';' /etc/supervisord.conf

UPNP=$(sed '4,7!d' /etc/supervisord.conf | grep -c '^#')
CAST=$(sed '9,12!d' /etc/supervisord.conf | grep -c '^#')

# Check if VAR is empty, and assign arch / if not empty, run with command and assign arch / if kill, and hasn't run (=0) then comment out
if [ -z "$AIRUPNP_VAR" ]; then
  sed -i 's;command=/bin/airupnp-x86-64 -l 1000:2000;command=/bin/airupnp-'"$ARCH_VAR"' -l 1000:2000;' /etc/supervisord.conf
elif [ "$AIRUPNP_VAR" != "kill" ]; then
  sed -i 's;command=/bin/airupnp-x86-64 -l 1000:2000;command=/bin/airupnp-'"$ARCH_VAR $AIRUPNP_VAR"';' /etc/supervisord.conf
elif [ "$AIRUPNP_VAR" = "kill" ] && [ "$UPNP" = 0 ]; then
    for i in {4..7}
    do
      sed -i ''$i'{s/^/#/}' /etc/supervisord.conf
    done
fi

# Check if VAR is empty, and assign arch / if not empty, run with command and assign arch / if kill, and hasn't run (=0) then comment out
if [ -z "$AIRCAST_VAR" ]; then
  sed -i 's;command=/bin/aircast-x86-64;command=/bin/aircast-'"$ARCH_VAR"';' /etc/supervisord.conf
elif [ "$AIRCAST_VAR" != "kill" ]; then
  sed -i 's;command=/bin/aircast-x86-64;command=/bin/aircast-'"$ARCH_VAR $AIRCAST_VAR"';' /etc/supervisord.conf
elif [ "$AIRCAST_VAR" = "kill" ] && [ "$CAST" = 0 ]; then
    for i in {9..12}
    do
      sed -i ''$i'{s/^/#/}' /etc/supervisord.conf
    done
fi